# Loki configuration optimized for local Docker Compose & Grafana Explore
# Includes volume limits and structured metadata support

auth_enabled: false # Keep auth disabled for local ease-of-use

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  # log_level: debug # Uncomment for verbose logging if needed

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem: # Using filesystem for local storage simplicity
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1 # Required for standalone mode
  ring:
    kvstore:
      store: inmemory # Suitable for single-instance local setup

schema_config:
  configs:
    - from: 2021-08-01 # Use a recent date for schema versioning
      store: boltdb-shipper # Recommended index store for performance and scalability
      object_store: filesystem # Store index files on the filesystem
      schema: v11 # Stable schema version
      index:
        prefix: index_
        period: 24h # Index period (daily buckets)

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    # shared_store: filesystem # Invalid here, belongs under common.storage or specific object store config if not filesystem
  filesystem: # Define the backend for the object store
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  # shared_store: filesystem # Invalid here
  compaction_interval: 10m # Compact chunks frequently for better query performance
  retention_enabled: true # Enable time and/or volume-based retention
  delete_request_store: filesystem # Required when retention_enabled is true
  # volume_enabled: true # Invalid here, belongs under limits_config
  retention_delete_delay: 2h
  retention_delete_worker_count: 1

# --- Ingester Configuration ---
ingester:
  lifecycler:
    # Manages ingester registration in the ring
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  # chunk_idle_period: 5m # How long to wait before flushing an idle chunk
  # max_chunk_age: 1h    # Max age before a chunk is flushed
  # chunk_target_size: 1048576 # 1MB target chunk size
  # max_transfer_retries: 3
  # structured_metadata: # Invalid block here. Use limits_config.allow_structured_metadata
  #   enabled: true

# --- Settings relevant for Grafana Explore performance ---
# frontend_worker: # Invalid block for recent Loki versions in monolithic mode
#   frontend_address: 127.0.0.1:9095
#   parallelism: 4

query_range:
  align_queries_with_step: true
  # max_query_length: 0 # Invalid key here
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

querier:
  max_concurrent: 8

# --- Limits Configuration ---
limits_config:
  # enforce_metric_name: false # Invalid key here
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 days
  # Volume limit: Max number of active streams allowed globally
  max_global_streams_per_user: 5000 # Adjust as needed for local testing
  max_query_series: 500 # Limit series returned by a query
  ingestion_rate_mb: 15
  ingestion_burst_size_mb: 20
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30
  allow_structured_metadata: false # Disabled due to incompatibility with schema v11 / boltdb-shipper
  volume_enabled: true

# --- Ruler (Alerting) ---
ruler:
  alertmanager_url: ''
  ring:
    kvstore:
      store: inmemory
  rule_path: /loki/rules-temp
  storage:
    type: local
    local:
      directory: /loki/rules
  enable_api: true

  # pattern_ingester: # Invalid block here
  #   enabled: true
